version: "3.9"

services:
  rails: &rails
    build:
      context: .
      dockerfile: docker/compose/development/rails/Dockerfile
      args:
        BUNDLER_VERSION: "${BUNDLER_VERSION}"
        POSTGRES_VERSION: "${POSTGRES_VERSION}"
        NODE_VERSION: "${NODE_VERSION}"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    env_file:
      - docker/compose/development/.development
    depends_on:
      - postgres

  app:
    <<: *rails
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    ports:
      - 5000:3000

  webpacker:
    <<: *rails
    ports:
      - "3035:3035"
    command: ./bin/webpack-dev-server
    depends_on:
      - postgres

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s


volumes:
  postgres:
  bundle:
