 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/treasury/outputs", type: :request do
  
  # Treasury::Output. As you add validations to Treasury::Output, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Treasury::Output.create! valid_attributes
      get treasury_outputs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      output = Treasury::Output.create! valid_attributes
      get treasury_output_url(treasury_output)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_treasury_output_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      output = Treasury::Output.create! valid_attributes
      get edit_treasury_output_url(treasury_output)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Treasury::Output" do
        expect {
          post treasury_outputs_url, params: { treasury_output: valid_attributes }
        }.to change(Treasury::Output, :count).by(1)
      end

      it "redirects to the created treasury_output" do
        post treasury_outputs_url, params: { treasury_output: valid_attributes }
        expect(response).to redirect_to(treasury_output_url(@treasury_output))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Treasury::Output" do
        expect {
          post treasury_outputs_url, params: { treasury_output: invalid_attributes }
        }.to change(Treasury::Output, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post treasury_outputs_url, params: { treasury_output: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested treasury_output" do
        output = Treasury::Output.create! valid_attributes
        patch treasury_output_url(treasury_output), params: { treasury_output: new_attributes }
        output.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the treasury_output" do
        output = Treasury::Output.create! valid_attributes
        patch treasury_output_url(treasury_output), params: { treasury_output: new_attributes }
        output.reload
        expect(response).to redirect_to(treasury_output_url(output))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        output = Treasury::Output.create! valid_attributes
        patch treasury_output_url(treasury_output), params: { treasury_output: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested treasury_output" do
      output = Treasury::Output.create! valid_attributes
      expect {
        delete treasury_output_url(treasury_output)
      }.to change(Treasury::Output, :count).by(-1)
    end

    it "redirects to the treasury_outputs list" do
      output = Treasury::Output.create! valid_attributes
      delete treasury_output_url(treasury_output)
      expect(response).to redirect_to(treasury_outputs_url)
    end
  end
end
