export const customerTypes = {
  GET_ALL_CUSTOMERS: 'GET_ALL_CUSTOMERS', 
  GET_ALL_CUSTOMERS_SUCCESS: 'GET_ALL_CUSTOMERS_SUCCESS', 
  GET_ALL_CUSTOMERS_ERROR: 'GET_ALL_CUSTOMERS_ERROR' ,
  IS_LOADING_GET_ALL_CUSTOMERS: 'IS_LOADING_GET_ALL_CUSTOMERS',

  CREATE_CUSTOMER: 'CREATE_CUSTOMER', 
  CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS', 
  CREATE_CUSTOMER_ERROR: 'CREATE_CUSTOMER_ERROR' ,
  IS_LOADING_CREATE_CUSTOMER: 'IS_LOADING_CREATE_CUSTOMER',

  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER', 
  UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS', 
  UPDATE_CUSTOMER_ERROR: 'UPDATE_CUSTOMER_ERROR' ,
  IS_LOADING_UPDATE_CUSTOMER: 'IS_LOADING_UPDATE_CUSTOMER',

  REPLACE_CUSTOMER: 'REPLACE_CUSTOMER',

  REMOVE_CUSTOMER_REQUEST: 'REMOVE_CUSTOMER_REQUEST',
  REMOVE_CUSTOMER_SUCCESS: 'REMOVE_CUSTOMER_SUCCESS',
  REMOVE_CUSTOMER_FAILURE: 'REMOVE_CUSTOMER_FAILURE',

  SEARCH_CUSTOMERS: 'SEARCH_CUSTOMERS', 
  SEARCH_CUSTOMERS_SUCCESS: 'SEARCH_CUSTOMERS_SUCCESS', 
  SEARCH_CUSTOMERS_ERROR: 'SEARCH_CUSTOMERS_ERROR' ,
  IS_LOADING_SEARCH_CUSTOMERS: 'IS_LOADING_SEARCH_CUSTOMERS',
  SELECT_CUSTOMER: 'SELECT_CUSTOMER'

  // GET_ALL_MY_VIDEOS: 'GET_ALL_MY_VIDEOS', 
  // GET_ALL_MY_VIDEOS_SUCCESS: 'GET_ALL_MY_VIDEOS_SUCCESS', 
  // GET_ALL_MY_VIDEOS_ERROR: 'GET_ALL_MY_VIDEOS_ERROR' ,
  // IS_LOADING_MY_VIDEOS: 'IS_LOADING_MY_VIDEOS',

  // CREATE_VIDEO_REQUEST: 'CREATE_VIDEO_REQUEST',
  // CREATE_VIDEO_SUCCESS: 'CREATE_VIDEO_SUCCESS',
  // CREATE_VIDEO_FAILURE: 'CREATE_VIDEO_FAILURE',

  // REMOVE_VIDEO_REQUEST: 'REMOVE_VIDEO_REQUEST',
  // REMOVE_VIDEO_SUCCESS: 'REMOVE_VIDEO_SUCCESS',
  // REMOVE_VIDEO_FAILURE: 'REMOVE_VIDEO_FAILURE',

  // GET_VIDEO_REQUEST: 'GET_VIDEO_REQUEST',
  // GET_VIDEO_SUCCESS: 'GET_VIDEO_SUCCESS',
  // GET_VIDEO_FAILURE: 'GET_VIDEO_FAILURE',

  // UPDATE_VIDEO_REQUEST: 'UPDATE_VIDEO_REQUEST',
  // UPDATE_VIDEO_SUCCESS: 'UPDATE_VIDEO_SUCCESS',
  // UPDATE_VIDEO_FAILURE: 'UPDATE_VIDEO_FAILURE',
};