export const saleTypes = {

  GET_ALL_ITEMS: 'GET_ALL_ITEMS',
  GET_ALL_CUSTOMERS_SUCCESS: 'GET_ALL_CUSTOMERS_SUCCESS',
  GET_ALL_ITEMS_SUCCESS: 'GET_ALL_ITEMS_SUCCESS', 
  GET_ALL_ITEMS_ERROR: 'GET_ALL_ITEMS_ERROR' ,
  IS_LOADING_GET_ALL_ITEMS: 'IS_LOADING_GET_ALL_ITEMS',

  
  SEARCH_ITEMS: 'SEARCH_ITEMS', 
  SEARCH_ITEMS_SUCCESS: 'SEARCH_ITEMS_SUCCESS', 
  SEARCH_ITEMS_ERROR: 'SEARCH_ITEMS_ERROR' ,
  IS_LOADING_SEARCH_ITEMS: 'IS_LOADING_SEARCH_ITEMS',

  SEARCH_CUSTOMERS: 'SEARCH_CUSTOMERS', 
  SEARCH_CUSTOMERS_SUCCESS: 'SEARCH_CUSTOMERS_SUCCESS', 
  SEARCH_CUSTOMERS_ERROR: 'SEARCH_CUSTOMERS_ERROR' ,
  IS_LOADING_SEARCH_CUSTOMERS: 'IS_LOADING_SEARCH_CUSTOMERS',

  SELECT_CUSTOMER_SUCCESS: 'SELECT_CUSTOMER_SUCCESS', 

  ADD_LINE_ITEM_SUCCESS: 'ADD_LINE_ITEM_SUCCESS',
  REMOVE_LINE_ITEM_SUCCESS: 'REMOVE_LINE_ITEM_SUCCESS',

  RESET_SALE_STATE: 'RESET_SALE_STATE',
  UPDATE_SALE_RESULT:'UPDATE_SALE_RESULT'
};