export const videoTypes = {
  GET_ALL_VIDEOS: 'GET_ALL_VIDEOS', 
  GET_ALL_VIDEOS_SUCCESS: 'GET_ALL_VIDEOS_SUCCESS', 
  GET_ALL_VIDEOS_ERROR: 'GET_ALL_VIDEOS_ERROR' ,
  IS_LOADING_VIDEOS: 'IS_LOADING_VIDEOS',

  GET_ALL_MY_VIDEOS: 'GET_ALL_MY_VIDEOS', 
  GET_ALL_MY_VIDEOS_SUCCESS: 'GET_ALL_MY_VIDEOS_SUCCESS', 
  GET_ALL_MY_VIDEOS_ERROR: 'GET_ALL_MY_VIDEOS_ERROR' ,
  IS_LOADING_MY_VIDEOS: 'IS_LOADING_MY_VIDEOS',

  CREATE_VIDEO_REQUEST: 'CREATE_VIDEO_REQUEST',
  CREATE_VIDEO_SUCCESS: 'CREATE_VIDEO_SUCCESS',
  CREATE_VIDEO_FAILURE: 'CREATE_VIDEO_FAILURE',

  REMOVE_VIDEO_REQUEST: 'REMOVE_VIDEO_REQUEST',
  REMOVE_VIDEO_SUCCESS: 'REMOVE_VIDEO_SUCCESS',
  REMOVE_VIDEO_FAILURE: 'REMOVE_VIDEO_FAILURE',

  GET_VIDEO_REQUEST: 'GET_VIDEO_REQUEST',
  GET_VIDEO_SUCCESS: 'GET_VIDEO_SUCCESS',
  GET_VIDEO_FAILURE: 'GET_VIDEO_FAILURE',

  UPDATE_VIDEO_REQUEST: 'UPDATE_VIDEO_REQUEST',
  UPDATE_VIDEO_SUCCESS: 'UPDATE_VIDEO_SUCCESS',
  UPDATE_VIDEO_FAILURE: 'UPDATE_VIDEO_FAILURE',
};