default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: your_user
  password: your_password

development:
  <<: *default
  database: pymesoft_development

test:
  <<: *default
  database: pymesoft_test

production:
  <<: *default
  database: pymesoft_production
  username:
  password:
